Repository openmobilityfoundation/mobility-data-specification, pull requests merged in 2020-03, with the labels that each got.

#457 Add language around targeting dev branch
  .github/pull_request_template.md
Labels: admin, documentation

#453 ReleaseGuidelines updates to reflect OMF process and 12 week dev cycle
  .github/ISSUE_TEMPLATE/release-candidate-review.md
  CONTRIBUTING.md
  ReleaseGuidelines.md
Labels: documentation

#468 Define "beta" features and replace the optional/required designation for endpoints
  general-information.md
  provider/README.md
Labels: Provider, documentation
