Repository openmobilityfoundation/mobility-data-specification, pull requests merged in 2020-09, with the labels that each got.

#572 Update State of Practice link
  README.md
Labels: minor update

#577 Add Mac .DS_Store files to git ignore
  .gitignore
Labels: minor update

#576 Policy JSON Schema
  agency/get_stops.json
  agency/get_vehicle.json
  agency/post_stops.json
  agency/post_vehicle.json
  policy/README.md
  policy/examples/README.md
  policy/examples/idle-time.json
  policy/examples/metered-parking-fees.json
  policy/examples/per-trip-fees.json
  policy/examples/prohibited-zone.json
  policy/examples/provider-cap.json
  policy/examples/speed-limits.json
  policy/examples/vehicle-row-fees.json
  policy/policy.json
  provider/README.md
  provider/events.json
  provider/status_changes.json
  provider/stops.json
  provider/trips.json
  provider/vehicles.json
  schema/README.md
  schema/agency.py
  schema/common.py
  schema/generate_schemas.py
  schema/policy.py
  schema/provider.py
  schema/templates/common.json
  schema/templates/policy/policy.json
  schema/templates/provider/trips.json
Labels: JSON Schema, Policy

#578 Release 1.0.0 - release branch to dev
  .gitignore
  MDS-state-machine-diagram.svg
  README.md
  ReleaseNotes.md
  agency/get_stops.json
  agency/get_vehicle.json
  agency/post_stops.json
  agency/post_vehicle.json
  agency/post_vehicle_event.json
  general-information.md
  policy/README.md
  policy/examples/README.md
  policy/examples/idle-time.json
  policy/examples/metered-parking-fees.json
  policy/examples/per-trip-fees.json
  policy/examples/prohibited-zone.json
  policy/examples/provider-cap.json
  policy/examples/speed-limits.json
  policy/examples/vehicle-row-fees.json
  policy/policy.json
  provider/README.md
  provider/events.json
  provider/status_changes.json
  provider/stops.json
  provider/trips.json
  provider/vehicles.json
  schema/README.md
  schema/agency.py
  schema/common.py
  schema/generate_schemas.py
  schema/policy.py
  schema/provider.py
  schema/templates/common.json
  schema/templates/policy/policy.json
  schema/templates/provider/trips.json
Labels: admin
