Repository openmobilityfoundation/mobility-data-specification, pull requests merged in 2020-05, with the labels that each got.

#490 Adding links to events and vehicles schema files
  provider/README.md
Labels: JSON Schema, Provider, documentation

#493 Release Process update
  .github/ISSUE_TEMPLATE/release-candidate-review.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/release-candidate.md
  .github/PULL_REQUEST_TEMPLATE/release-final.md
  ReleaseGuidelines.md
Labels: admin

#494 Release Candidate 0.4.1
  .github/ISSUE_TEMPLATE/release-candidate-review.md
  .github/PULL_REQUEST_TEMPLATE/default.md
  .github/PULL_REQUEST_TEMPLATE/release-candidate.md
  .github/PULL_REQUEST_TEMPLATE/release-final.md
  ReleaseGuidelines.md
  ReleaseNotes.md
  agency/get_vehicle.json
  agency/post_vehicle_event.json
  general-information.md
  provider/README.md
  schema/templates/common.json
Labels: admin

#479 Clarified review and decision making for beta features
  general-information.md
Labels: Provider

#478 Clarified that /vehicles is not intended to replace GBFS
  provider/README.md
Labels: Provider
