Repository openmobilityfoundation/mobility-data-specification, pull requests merged in 2023-12, with the labels that each got.

#882 Clarify which vehicles to include in the `/vehicles` endpoint
  provider/README.md
Labels: Provider, documentation

#874 Fixing broken links in data-types markdown document
  data-types.md
  provider/README.md
Labels: minor update

#892 Add Nextbike
  providers.csv
Labels: identifier change

#893 Release 2.0.1
  ReleaseNotes.md
  data-types.md
  modes/car-share.md
  provider/README.md
  providers.csv
Labels: admin
